import type { Metadata } from "next";
import "@crosmos/ui/globals.css";

export const metadata: Metadata = {
	title: "Crosmos",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
