import type { GraphEdge, GraphNode } from "../types";

const now = "2026-05-17T00:00:00Z";

export const MOCK_NODES: GraphNode[] = [
	// User cluster (25 nodes)
	{
		id: "u1",
		name: "Alice Johnson",
		entity_type: "User",
		edge_count: 4,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u2",
		name: "Bob Smith",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u3",
		name: "Carol Williams",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u4",
		name: "David Brown",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u5",
		name: "Eva Martinez",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u6",
		name: "Frank Garcia",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u7",
		name: "Grace Lee",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u8",
		name: "Henry Wilson",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u9",
		name: "Irene Davis",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u10",
		name: "Jack Taylor",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u11",
		name: "Karen Anderson",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u12",
		name: "Leo Thomas",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u13",
		name: "Mia Jackson",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u14",
		name: "Noah White",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u15",
		name: "Olivia Harris",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u16",
		name: "Paul Clark",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u17",
		name: "Quinn Lewis",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u18",
		name: "Rachel Robinson",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u19",
		name: "Sam Walker",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u20",
		name: "Tina Hall",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u21",
		name: "Uma Allen",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u22",
		name: "Victor Young",
		entity_type: "User",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u23",
		name: "Wendy King",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u24",
		name: "Xavier Wright",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "u25",
		name: "Yara Lopez",
		entity_type: "User",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},

	// Organization cluster (20 nodes)
	{
		id: "o1",
		name: "Acme Corp",
		entity_type: "Organization",
		edge_count: 5,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o2",
		name: "Globex Industries",
		entity_type: "Organization",
		edge_count: 4,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o3",
		name: "Initech Solutions",
		entity_type: "Organization",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o4",
		name: "Umbrella Labs",
		entity_type: "Organization",
		edge_count: 4,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o5",
		name: "Stark Enterprises",
		entity_type: "Organization",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o6",
		name: "Wayne Technologies",
		entity_type: "Organization",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o7",
		name: "Cyberdyne Systems",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o8",
		name: "Oscorp",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o9",
		name: "LexCorp",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o10",
		name: "Soylent Corp",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o11",
		name: "Tyrell Corp",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o12",
		name: "Weyland-Yutani",
		entity_type: "Organization",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o13",
		name: "Massive Dynamic",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o14",
		name: "Pied Piper",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o15",
		name: "Hooli",
		entity_type: "Organization",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o16",
		name: "Vehement Capital",
		entity_type: "Organization",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o17",
		name: "Nucleus",
		entity_type: "Organization",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o18",
		name: "Barkbox",
		entity_type: "Organization",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o19",
		name: "Endframe",
		entity_type: "Organization",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "o20",
		name: "Raviga",
		entity_type: "Organization",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},

	// Project cluster (25 nodes)
	{
		id: "p1",
		name: "Project Alpha",
		entity_type: "Project",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p2",
		name: "Project Beta",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p3",
		name: "Project Gamma",
		entity_type: "Project",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p4",
		name: "Project Delta",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p5",
		name: "Project Epsilon",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p6",
		name: "Project Zeta",
		entity_type: "Project",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p7",
		name: "Project Eta",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p8",
		name: "Project Theta",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p9",
		name: "Project Iota",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p10",
		name: "Project Kappa",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p11",
		name: "Migration Pipeline",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p12",
		name: "Data Lake Initiative",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p13",
		name: "Cloud Native Refactor",
		entity_type: "Project",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p14",
		name: "API Gateway v2",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p15",
		name: "ML Platform",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p16",
		name: "Auth Service Rewrite",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p17",
		name: "Dashboard Redesign",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p18",
		name: "Mobile App v3",
		entity_type: "Project",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p19",
		name: "Search Optimization",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p20",
		name: "Notification System",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p21",
		name: "CI/CD Overhaul",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p22",
		name: "Monitoring Stack",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p23",
		name: "Schema Migration",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p24",
		name: "Performance Audit",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "p25",
		name: "Security Hardening",
		entity_type: "Project",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},

	// Technology cluster (30 nodes)
	{
		id: "t1",
		name: "React",
		entity_type: "Technology",
		edge_count: 4,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t2",
		name: "TypeScript",
		entity_type: "Technology",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t3",
		name: "Node.js",
		entity_type: "Technology",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t4",
		name: "PostgreSQL",
		entity_type: "Technology",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t5",
		name: "Redis",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t6",
		name: "Docker",
		entity_type: "Technology",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t7",
		name: "Kubernetes",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t8",
		name: "GraphQL",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t9",
		name: "REST API",
		entity_type: "Technology",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t10",
		name: "Next.js",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t11",
		name: "Tailwind CSS",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t12",
		name: "Prisma",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t13",
		name: "tRPC",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t14",
		name: "SWR",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t15",
		name: "Zustand",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t16",
		name: "Vite",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t17",
		name: "ESLint",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t18",
		name: "Prettier",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t19",
		name: "Biome",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t20",
		name: "Turborepo",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t21",
		name: "AWS Lambda",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t22",
		name: "S3",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t23",
		name: "CloudFront",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t24",
		name: "Terraform",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t25",
		name: "GitHub Actions",
		entity_type: "Technology",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t26",
		name: "Jest",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t27",
		name: "Playwright",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t28",
		name: "Storybook",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t29",
		name: "Figma",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "t30",
		name: "Linear",
		entity_type: "Technology",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},

	// Location cluster (15 nodes)
	{
		id: "l1",
		name: "San Francisco",
		entity_type: "Location",
		edge_count: 3,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l2",
		name: "New York",
		entity_type: "Location",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l3",
		name: "London",
		entity_type: "Location",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l4",
		name: "Berlin",
		entity_type: "Location",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l5",
		name: "Tokyo",
		entity_type: "Location",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l6",
		name: "Toronto",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l7",
		name: "Austin",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l8",
		name: "Seattle",
		entity_type: "Location",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l9",
		name: "Boston",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l10",
		name: "Chicago",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l11",
		name: "Denver",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l12",
		name: "Sydney",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l13",
		name: "Singapore",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l14",
		name: "Bangalore",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "l15",
		name: "Amsterdam",
		entity_type: "Location",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},

	// Document cluster (20 nodes)
	{
		id: "d1",
		name: "Architecture Decision Record #42",
		entity_type: "Document",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d2",
		name: "API Design Guidelines",
		entity_type: "Document",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d3",
		name: "Onboarding Handbook",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d4",
		name: "Security Policy v3",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d5",
		name: "Deployment Runbook",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d6",
		name: "Incident Response Plan",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d7",
		name: "Database Schema v12",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d8",
		name: "Style Guide 2026",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d9",
		name: "Sprint Retrospective Q1",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d10",
		name: "Product Requirements Doc",
		entity_type: "Document",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d11",
		name: "Technical Spec: Auth",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d12",
		name: "Migration Plan: v2 to v3",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d13",
		name: "Code Review Checklist",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d14",
		name: "Release Notes 4.0",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d15",
		name: "Performance Benchmarks",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d16",
		name: "UX Research Report",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d17",
		name: "Compliance Audit 2026",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d18",
		name: "Budget Forecast Q2",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d19",
		name: "Team OKRs",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "d20",
		name: "Vendor Comparison Matrix",
		entity_type: "Document",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},

	// Concept cluster (19 nodes)
	{
		id: "c1",
		name: "Microservices",
		entity_type: "Concept",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c2",
		name: "Event-Driven Architecture",
		entity_type: "Concept",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c3",
		name: "Domain-Driven Design",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c4",
		name: "Test-Driven Development",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c5",
		name: "Continuous Integration",
		entity_type: "Concept",
		edge_count: 2,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c6",
		name: "Zero Trust Security",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c7",
		name: "Serverless Computing",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c8",
		name: "Infrastructure as Code",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c9",
		name: "Observability",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c10",
		name: "Rate Limiting",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c11",
		name: "Caching Strategy",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c12",
		name: "Data Partitioning",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c13",
		name: "API Versioning",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c14",
		name: "Feature Flags",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c15",
		name: "A/B Testing",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c16",
		name: "Blue-Green Deployment",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c17",
		name: "Canary Release",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c18",
		name: "Chaos Engineering",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
	{
		id: "c19",
		name: "Service Mesh",
		entity_type: "Concept",
		edge_count: 1,
		created_at: now,
		updated_at: now,
	},
];

export const MOCK_EDGES: GraphEdge[] = [
	// User -> Organization edges (works_for)
	{
		id: "e1",
		source_entity_id: "u1",
		target_entity_id: "o1",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e2",
		source_entity_id: "u2",
		target_entity_id: "o1",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e3",
		source_entity_id: "u3",
		target_entity_id: "o2",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e4",
		source_entity_id: "u4",
		target_entity_id: "o2",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e5",
		source_entity_id: "u5",
		target_entity_id: "o3",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e6",
		source_entity_id: "u6",
		target_entity_id: "o3",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e7",
		source_entity_id: "u7",
		target_entity_id: "o4",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e8",
		source_entity_id: "u8",
		target_entity_id: "o4",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e9",
		source_entity_id: "u9",
		target_entity_id: "o5",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e10",
		source_entity_id: "u10",
		target_entity_id: "o5",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e11",
		source_entity_id: "u11",
		target_entity_id: "o6",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e12",
		source_entity_id: "u12",
		target_entity_id: "o6",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e13",
		source_entity_id: "u13",
		target_entity_id: "o7",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e14",
		source_entity_id: "u14",
		target_entity_id: "o8",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e15",
		source_entity_id: "u15",
		target_entity_id: "o9",
		relation_type: "works_for",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// User -> Project edges (assigned_to)
	{
		id: "e16",
		source_entity_id: "u1",
		target_entity_id: "p1",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e17",
		source_entity_id: "u2",
		target_entity_id: "p1",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e18",
		source_entity_id: "u3",
		target_entity_id: "p2",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e19",
		source_entity_id: "u4",
		target_entity_id: "p3",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e20",
		source_entity_id: "u5",
		target_entity_id: "p3",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e21",
		source_entity_id: "u6",
		target_entity_id: "p4",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e22",
		source_entity_id: "u7",
		target_entity_id: "p5",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e23",
		source_entity_id: "u8",
		target_entity_id: "p6",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e24",
		source_entity_id: "u9",
		target_entity_id: "p6",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e25",
		source_entity_id: "u10",
		target_entity_id: "p7",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e26",
		source_entity_id: "u11",
		target_entity_id: "p8",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e27",
		source_entity_id: "u12",
		target_entity_id: "p9",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e28",
		source_entity_id: "u13",
		target_entity_id: "p10",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e29",
		source_entity_id: "u14",
		target_entity_id: "p11",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e30",
		source_entity_id: "u15",
		target_entity_id: "p12",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e31",
		source_entity_id: "u16",
		target_entity_id: "p13",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e32",
		source_entity_id: "u17",
		target_entity_id: "p13",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e33",
		source_entity_id: "u18",
		target_entity_id: "p14",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e34",
		source_entity_id: "u19",
		target_entity_id: "p15",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e35",
		source_entity_id: "u20",
		target_entity_id: "p16",
		relation_type: "assigned_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// User -> Location edges (located_in)
	{
		id: "e36",
		source_entity_id: "u1",
		target_entity_id: "l1",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e37",
		source_entity_id: "u2",
		target_entity_id: "l2",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e38",
		source_entity_id: "u3",
		target_entity_id: "l3",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e39",
		source_entity_id: "u4",
		target_entity_id: "l4",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e40",
		source_entity_id: "u5",
		target_entity_id: "l5",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e41",
		source_entity_id: "u6",
		target_entity_id: "l6",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e42",
		source_entity_id: "u7",
		target_entity_id: "l7",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e43",
		source_entity_id: "u8",
		target_entity_id: "l8",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e44",
		source_entity_id: "u9",
		target_entity_id: "l9",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e45",
		source_entity_id: "u10",
		target_entity_id: "l10",
		relation_type: "located_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// User -> User edges (collaborates_with)
	{
		id: "e46",
		source_entity_id: "u1",
		target_entity_id: "u3",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e47",
		source_entity_id: "u2",
		target_entity_id: "u5",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e48",
		source_entity_id: "u4",
		target_entity_id: "u7",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e49",
		source_entity_id: "u6",
		target_entity_id: "u9",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e50",
		source_entity_id: "u8",
		target_entity_id: "u11",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e51",
		source_entity_id: "u10",
		target_entity_id: "u13",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e52",
		source_entity_id: "u12",
		target_entity_id: "u15",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e53",
		source_entity_id: "u14",
		target_entity_id: "u17",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e54",
		source_entity_id: "u16",
		target_entity_id: "u19",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e55",
		source_entity_id: "u18",
		target_entity_id: "u21",
		relation_type: "collaborates_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Organization -> Project edges (owns)
	{
		id: "e56",
		source_entity_id: "o1",
		target_entity_id: "p1",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e57",
		source_entity_id: "o1",
		target_entity_id: "p2",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e58",
		source_entity_id: "o2",
		target_entity_id: "p3",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e59",
		source_entity_id: "o2",
		target_entity_id: "p4",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e60",
		source_entity_id: "o3",
		target_entity_id: "p5",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e61",
		source_entity_id: "o4",
		target_entity_id: "p6",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e62",
		source_entity_id: "o4",
		target_entity_id: "p7",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e63",
		source_entity_id: "o5",
		target_entity_id: "p8",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e64",
		source_entity_id: "o6",
		target_entity_id: "p9",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e65",
		source_entity_id: "o7",
		target_entity_id: "p10",
		relation_type: "owns",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Organization -> Location edges (headquartered_in)
	{
		id: "e66",
		source_entity_id: "o1",
		target_entity_id: "l1",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e67",
		source_entity_id: "o2",
		target_entity_id: "l2",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e68",
		source_entity_id: "o3",
		target_entity_id: "l3",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e69",
		source_entity_id: "o4",
		target_entity_id: "l4",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e70",
		source_entity_id: "o5",
		target_entity_id: "l5",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e71",
		source_entity_id: "o6",
		target_entity_id: "l8",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e72",
		source_entity_id: "o7",
		target_entity_id: "l11",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e73",
		source_entity_id: "o8",
		target_entity_id: "l12",
		relation_type: "headquartered_in",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Project -> Technology edges (uses)
	{
		id: "e74",
		source_entity_id: "p1",
		target_entity_id: "t1",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e75",
		source_entity_id: "p1",
		target_entity_id: "t2",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e76",
		source_entity_id: "p2",
		target_entity_id: "t3",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e77",
		source_entity_id: "p3",
		target_entity_id: "t4",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e78",
		source_entity_id: "p3",
		target_entity_id: "t10",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e79",
		source_entity_id: "p4",
		target_entity_id: "t5",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e80",
		source_entity_id: "p5",
		target_entity_id: "t6",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e81",
		source_entity_id: "p6",
		target_entity_id: "t7",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e82",
		source_entity_id: "p7",
		target_entity_id: "t8",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e83",
		source_entity_id: "p8",
		target_entity_id: "t9",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e84",
		source_entity_id: "p9",
		target_entity_id: "t11",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e85",
		source_entity_id: "p10",
		target_entity_id: "t12",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e86",
		source_entity_id: "p11",
		target_entity_id: "t13",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e87",
		source_entity_id: "p12",
		target_entity_id: "t14",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e88",
		source_entity_id: "p13",
		target_entity_id: "t15",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e89",
		source_entity_id: "p14",
		target_entity_id: "t16",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e90",
		source_entity_id: "p15",
		target_entity_id: "t21",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e91",
		source_entity_id: "p16",
		target_entity_id: "t22",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e92",
		source_entity_id: "p17",
		target_entity_id: "t23",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e93",
		source_entity_id: "p18",
		target_entity_id: "t24",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e94",
		source_entity_id: "p19",
		target_entity_id: "t25",
		relation_type: "uses",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Technology -> Technology edges (compatible_with)
	{
		id: "e95",
		source_entity_id: "t1",
		target_entity_id: "t2",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e96",
		source_entity_id: "t2",
		target_entity_id: "t3",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e97",
		source_entity_id: "t3",
		target_entity_id: "t4",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e98",
		source_entity_id: "t6",
		target_entity_id: "t7",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e99",
		source_entity_id: "t10",
		target_entity_id: "t1",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e100",
		source_entity_id: "t11",
		target_entity_id: "t10",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e101",
		source_entity_id: "t12",
		target_entity_id: "t4",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e102",
		source_entity_id: "t21",
		target_entity_id: "t22",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e103",
		source_entity_id: "t24",
		target_entity_id: "t21",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e104",
		source_entity_id: "t25",
		target_entity_id: "t6",
		relation_type: "compatible_with",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Project -> Document edges (has_document)
	{
		id: "e105",
		source_entity_id: "p1",
		target_entity_id: "d1",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e106",
		source_entity_id: "p1",
		target_entity_id: "d2",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e107",
		source_entity_id: "p2",
		target_entity_id: "d3",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e108",
		source_entity_id: "p3",
		target_entity_id: "d4",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e109",
		source_entity_id: "p4",
		target_entity_id: "d5",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e110",
		source_entity_id: "p5",
		target_entity_id: "d6",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e111",
		source_entity_id: "p6",
		target_entity_id: "d7",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e112",
		source_entity_id: "p7",
		target_entity_id: "d8",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e113",
		source_entity_id: "p8",
		target_entity_id: "d9",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e114",
		source_entity_id: "p9",
		target_entity_id: "d10",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e115",
		source_entity_id: "p10",
		target_entity_id: "d11",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e116",
		source_entity_id: "p11",
		target_entity_id: "d12",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e117",
		source_entity_id: "p12",
		target_entity_id: "d13",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e118",
		source_entity_id: "p13",
		target_entity_id: "d14",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e119",
		source_entity_id: "p14",
		target_entity_id: "d15",
		relation_type: "has_document",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Project -> Concept edges (implements)
	{
		id: "e120",
		source_entity_id: "p1",
		target_entity_id: "c1",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e121",
		source_entity_id: "p2",
		target_entity_id: "c2",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e122",
		source_entity_id: "p3",
		target_entity_id: "c3",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e123",
		source_entity_id: "p4",
		target_entity_id: "c4",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e124",
		source_entity_id: "p5",
		target_entity_id: "c5",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e125",
		source_entity_id: "p6",
		target_entity_id: "c6",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e126",
		source_entity_id: "p7",
		target_entity_id: "c7",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e127",
		source_entity_id: "p8",
		target_entity_id: "c8",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e128",
		source_entity_id: "p9",
		target_entity_id: "c9",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e129",
		source_entity_id: "p10",
		target_entity_id: "c10",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e130",
		source_entity_id: "p11",
		target_entity_id: "c11",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e131",
		source_entity_id: "p12",
		target_entity_id: "c12",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e132",
		source_entity_id: "p13",
		target_entity_id: "c13",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e133",
		source_entity_id: "p14",
		target_entity_id: "c14",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e134",
		source_entity_id: "p15",
		target_entity_id: "c15",
		relation_type: "implements",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},

	// Concept -> Concept edges (related_to)
	{
		id: "e135",
		source_entity_id: "c1",
		target_entity_id: "c2",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e136",
		source_entity_id: "c2",
		target_entity_id: "c7",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e137",
		source_entity_id: "c5",
		target_entity_id: "c16",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e138",
		source_entity_id: "c6",
		target_entity_id: "c9",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e139",
		source_entity_id: "c8",
		target_entity_id: "c7",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e140",
		source_entity_id: "c16",
		target_entity_id: "c17",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e141",
		source_entity_id: "c18",
		target_entity_id: "c19",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e142",
		source_entity_id: "c11",
		target_entity_id: "c5",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e143",
		source_entity_id: "c10",
		target_entity_id: "c13",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e144",
		source_entity_id: "c3",
		target_entity_id: "c1",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
	{
		id: "e145",
		source_entity_id: "c4",
		target_entity_id: "c5",
		relation_type: "related_to",
		confidence: 1,
		valid_from: now,
		recorded_at: now,
	},
];
